name: Report Notifier CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'infrastructure/modules/services/report-notifier/**'
      - 'infrastructure/prod/services/report-notifier/**'
      - 'infrastructure/stage/services/report-notifier/**'
      - 'services/report-notifier/**'
      - '.github/workflows/report-notifier-ci-cd.yml'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'infrastructure/modules/services/report-notifier/**'
      - 'infrastructure/prod/services/report-notifier/**'
      - 'infrastructure/stage/services/report-notifier/**'
      - 'services/report-notifier/**'
      - '.github/workflows/report-notifier-ci-cd.yml'
      - '.github/workflows/terraform.yml'

permissions:
  id-token: write       # Required for OIDC authentication with AWS
  contents: read        # Required to check out the repository's code
  pull-requests: write  # Required to comment on pull requests

env:
  ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
  AWS_REGION: us-east-1

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'stage' }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
          cache: 'npm'
          cache-dependency-path: services/report-notifier/package-lock.json

      - name: Install Dependencies
        working-directory: ./services/report-notifier
        run: npm install

      - name: Run Unit Tests
        working-directory: ./services/report-notifier
        run: npm run test:ci

  build:
    name: Build and Package Lambda Function
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'stage' }}
    outputs:
      source_code_hash: ${{ steps.calc_hash.outputs.hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
          cache: 'npm'
          cache-dependency-path: services/report-notifier/package-lock.json

      - name: Install Dependencies
        working-directory: ./services/report-notifier
        run: npm install

      - name: Build Code
        working-directory: ./services/report-notifier
        run: npm run build

      - name: Package Lambda function
        run: zip -j function.zip services/report-notifier/dist/*

      - name: Calculate Lambda source hash
        id: calc_hash
        run: echo "hash=$(openssl dgst -sha256 -binary function.zip | base64)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload artifact to S3
        run: aws s3 cp function.zip s3://${{ vars.S3_ARTIFACT_BUCKET }}/report-notifier.zip

  deploy:
    needs: [ test, build ]
    uses: ./.github/workflows/terraform.yml
    with:
      working-directory: ${{ github.ref_name == 'main' && 'infrastructure/prod/services/report-notifier' || 'infrastructure/stage/services/report-notifier' }}
      apply: ${{ github.event_name == 'push' }}
      terraform-variables: '-var="source_code_hash=${{ needs.build.outputs.source_code_hash }}"'
    secrets:
      ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}